on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4   # https://github.com/actions/setup-python
        with:
          python-version: '3.10'

      - name: Install Requirements 
        run:  pip install flask

      - name: Build and push Docker image
        run: |
            echo ${{ secrets.GCP_SA_KEY_BASE64 }} | base64 --decode > gcp_sa_key.json
            gcloud auth activate-service-account --key-file=gcp_sa_key.json
            gcloud config set project grupo-15-384916
            gcloud auth configure-docker us-west1-docker.pkg.dev
            docker build -t us-west1-docker.pkg.dev/grupo-15-384916/spotrepo/backend:${{ github.sha }} .
            docker push us-west1-docker.pkg.dev/grupo-15-384916/spotrepo/backend:${{ github.sha }}
            rm gcp_sa_key.json

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Instalar o Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
          export_default_credentials: true 
      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy spot-backend --image us-west1-docker.pkg.dev/${GCP_PROJECT_ID}/spotrepo/backend:{{ github.sha }} --region us-west1 --platform managed --allow-unauthenticated
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GITHUB_SHA: ${{ github.sha }}